module.exports = [
  // Level 1 (1-35)
  {id:1,level:1,question:"ما المقصود بالبرمجة؟",options:["إصلاح أجهزة الكمبيوتر","كتابة تعليمات للحاسوب لتنفيذ مهمة معينة","تصميم الصور","استخدام الإنترنت"],answer:1},
  {id:2,level:1,question:"أي لغة برمجة يركز عليها المنهج؟",options:["Java","C++","Python","PHP"],answer:2},
  {id:3,level:1,question:"أي مما يلي يعد من مميزات Python؟",options:["صعبة التعلم","مناسبة للمبتدئين","تعمل على نظام واحد فقط","لا تدعم الذكاء الاصطناعي"],answer:1},
  {id:4,level:1,question:"ما هو المكون المسؤول عن تنفيذ التعليمات داخل الحاسوب؟",options:["RAM","CPU","Keyboard","Monitor"],answer:1},
  {id:5,level:1,question:"يرمز CPU إلى:",options:["Central Programming Unit","Central Processing Unit","Computer Program Unit","Central Power Unit"],answer:1},
  {id:6,level:1,question:"أي نوع من الذاكرة يعتبر مؤقتًا؟",options:["HDD","SSD","RAM","ROM"],answer:2},
  {id:7,level:1,question:"أي نوع من الذاكرة يحتفظ بالبيانات بعد إيقاف تشغيل الجهاز؟",options:["RAM","Cache","HDD","Register"],answer:2},
  {id:8,level:1,question:"أي من التالي يعد جهاز إدخال (Input)؟",options:["الشاشة","الطابعة","لوحة المفاتيح","السماعات"],answer:2},
  {id:9,level:1,question:"أي من التالي يعد جهاز إخراج (Output)؟",options:["Mouse","Keyboard","Monitor","Scanner"],answer:2},
  {id:10,level:1,question:"ما وظيفة Flowchart؟",options:["كتابة الأكواد","رسم خطوات حل المشكلة","تصميم المواقع","إنشاء قواعد البيانات"],answer:1},
  {id:11,level:1,question:"أي شكل يستخدم لتمثيل البداية والنهاية في Flowchart؟",options:["Rectangle","Diamond","Oval","Parallelogram"],answer:2},
  {id:12,level:1,question:"أي شكل يستخدم لاتخاذ قرار (Decision)؟",options:["Oval","Diamond","Rectangle","Circle"],answer:1},
  {id:13,level:1,question:"ما هو المتغير (Variable)؟",options:["برنامج","مكان لتخزين البيانات","جهاز إدخال","نوع بيانات"],answer:1},
  {id:14,level:1,question:"أي من الأسماء التالية صالح كاسم متغير؟",options:["2name","my name","student_age","class"],answer:2},
  {id:15,level:1,question:"أي من التالي يمثل عددًا صحيحًا (int)؟",options:["5","5.5",'"5"',"True"],answer:0},
  {id:16,level:1,question:"أي من التالي يمثل عددًا عشريًا (float)؟",options:["20",'"20"',"20.5","False"],answer:2},
  {id:17,level:1,question:"أي من التالي يمثل نصًا (str)؟",options:['"Python"',"100","True","5.2"],answer:0},
  {id:18,level:1,question:"أي من التالي يمثل قيمة منطقية (bool)؟",options:["0",'"True"',"True","3.14"],answer:2},
  {id:19,level:1,question:"أي دالة تستخدم لمعرفة نوع البيانات؟",options:["print()","input()","type()","len()"],answer:2},
  {id:20,level:1,question:"أي دالة تستخدم لعرض البيانات على الشاشة؟",options:["input()","print()","type()","int()"],answer:1},
  {id:21,level:1,question:"أي دالة تُستخدم لاستقبال بيانات من المستخدم؟",options:["print()","input()","type()","float()"],answer:1},
  {id:22,level:1,question:"القيمة التي تُرجعها الدالة input() تكون من النوع:",options:["int","float","str","bool"],answer:2},
  {id:23,level:1,question:"لتحويل قيمة أدخلها المستخدم إلى عدد صحيح نستخدم:",options:["str()","bool()","int()","type()"],answer:2},
  {id:24,level:1,question:"ما ناتج العملية التالية؟",isCode:true,code:`5 + 3`,options:["15","8","2","53"],answer:1},
  {id:25,level:1,question:"أي عامل يستخدم في عملية الطرح؟",options:["+","*","-","/"],answer:2},
  {id:26,level:1,question:"أي عامل يستخدم في عملية الضرب؟",options:["+","*","/","%"],answer:1},
  {id:27,level:1,question:"أي عامل يستخدم في القسمة؟",options:["/","%","//","**"],answer:0},
  {id:28,level:1,question:"أي عامل يُستخدم لحساب باقي القسمة؟",options:["//","%","*","+"],answer:1},
  {id:29,level:1,question:"أي عامل يستخدم لتمثيل الأس (Power)؟",options:["*","%","**","//"],answer:2},
  {id:30,level:1,question:"ما ناتج المقارنة التالية؟",isCode:true,code:`5 == 5`,options:["False","True","Error","5"],answer:1},
  {id:31,level:1,question:"أي عامل يعني \"لا يساوي\"؟",options:["==","=","!=","<="],answer:2},
  {id:32,level:1,question:"أي عامل يعني \"أكبر من أو يساوي\"؟",options:[">","<",">=","=="],answer:2},
  {id:33,level:1,question:"أي عملية منطقية تعني أن الشرطين يجب أن يكونا صحيحين؟",options:["or","and","not","if"],answer:1},
  {id:34,level:1,question:"أي عملية منطقية تعكس القيمة المنطقية؟",options:["and","or","not","elif"],answer:2},
  {id:35,level:1,question:"تستخدم الجملة الشرطية if من أجل:",options:["تكرار الكود","تخزين البيانات","اتخاذ قرار بناءً على شرط","تعريف متغير"],answer:2},

  // Level 2 (36-70)
  {id:36,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 10\nprint(x)`,options:["x","0","10","Error"],answer:2},
  {id:37,level:2,question:"ما نوع المتغير التالي؟",isCode:true,code:`price = 15.75`,options:["int","float","str","bool"],answer:1},
  {id:38,level:2,question:"ما نوع المتغير التالي؟",isCode:true,code:`student = True`,options:["str","bool","int","float"],answer:1},
  {id:39,level:2,question:"أي من أسماء المتغيرات التالية غير صحيح؟",options:["student_name","totalMarks","my grade","age"],answer:2},
  {id:40,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type("50"))`,options:["int","float","str","bool"],answer:2},
  {id:41,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type(50))`,options:["float","str","int","bool"],answer:2},
  {id:42,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type(False))`,options:["bool","int","str","float"],answer:0},
  {id:43,level:2,question:"أي عملية حسابية تعطي الناتج 15؟",options:["20 - 5","5 × 3","30 ÷ 2","جميع ما سبق"],answer:3},
  {id:44,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(12 % 5)`,options:["2","1","5","0"],answer:0},
  {id:45,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(12 // 5)`,options:["2.4","2","3","12"],answer:1},
  {id:46,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(2 ** 4)`,options:["8","16","6","24"],answer:1},
  {id:47,level:2,question:"ما ناتج المقارنة التالية؟",isCode:true,code:`10 > 15`,options:["True","False","Error","10"],answer:1},
  {id:48,level:2,question:"ما ناتج المقارنة التالية؟",isCode:true,code:`20 >= 20`,options:["True","False","Error","20"],answer:0},
  {id:49,level:2,question:"ما ناتج المقارنة التالية؟",isCode:true,code:`7 != 7`,options:["True","False","Error","7"],answer:1},
  {id:50,level:2,question:"إذا كانت x = 8، فما ناتج الكود التالي؟",isCode:true,code:`x = 8\nprint(x < 10 and x > 5)`,options:["True","False","Error","8"],answer:0},
  {id:51,level:2,question:"إذا كانت x = 4، فما ناتج الكود التالي؟",isCode:true,code:`x = 4\nprint(x > 10 or x < 5)`,options:["True","False","Error","4"],answer:0},
  {id:52,level:2,question:"إذا كانت x = 7، فما ناتج الكود التالي؟",isCode:true,code:`x = 7\nprint(not(x > 5))`,options:["True","False","Error","7"],answer:1},
  {id:53,level:2,question:"ما وظيفة جملة if؟",options:["تكرار الأوامر","اتخاذ قرار عند تحقق شرط","إنشاء متغير","طباعة البيانات فقط"],answer:1},
  {id:54,level:2,question:"إذا كانت grade = 80 وكان الشرط if grade >= 50: فهل سيتم تنفيذ الكود داخل if؟",isCode:true,code:`grade = 80\nif grade >= 50:`,options:["نعم","لا","يحدث خطأ","يتوقف البرنامج"],answer:0},
  {id:55,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`grade = 30\nif grade >= 50:\n    print("Pass")\nelse:\n    print("Fail")`,options:["Pass","Fail","30","Error"],answer:1},
  {id:56,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 12\ny = 8\nprint(x + y)`,options:["4","20","96","128"],answer:1},
  {id:57,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`a = 20\nb = 5\nprint(a / b)`,options:["4","4.0","5","25"],answer:1},
  {id:58,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 7\nprint(x % 2)`,options:["0","1","2","7"],answer:1},
  {id:59,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type(15.0))`,options:["int","str","float","bool"],answer:2},
  {id:60,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`name = "Ali"\nprint(type(name))`,options:["int","float","str","bool"],answer:2},
  {id:61,level:2,question:"إذا كانت قيمة المتغير age = 16 فما ناتج المقارنة age >= 18؟",isCode:true,code:`age = 16\nprint(age >= 18)`,options:["True","False","Error","16"],answer:1},
  {id:62,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 5\nprint(x == 5)`,options:["True","False","Error","5"],answer:0},
  {id:63,level:2,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 9\nprint(x != 10)`,options:["False","True","Error","9"],answer:1},
  {id:64,level:2,question:"إذا كانت x = 6، فما ناتج: x > 3 and x < 10",isCode:true,code:`x = 6\nprint(x > 3 and x < 10)`,options:["True","False","Error","6"],answer:0},
  {id:65,level:2,question:"إذا كانت x = 2، فما ناتج: x > 5 or x == 2",isCode:true,code:`x = 2\nprint(x > 5 or x == 2)`,options:["True","False","Error","2"],answer:0},
  {id:66,level:2,question:"إذا كانت x = 4، فما ناتج: not(x < 2)",isCode:true,code:`x = 4\nprint(not(x < 2))`,options:["True","False","Error","4"],answer:0},
  {id:67,level:2,question:"أي من التالي يُستخدم لتحويل النص إلى عدد صحيح؟",options:["print()","type()","int()","input()"],answer:2},
  {id:68,level:2,question:"ما ناتج الكود التالي إذا أدخل المستخدم القيمة 25؟",isCode:true,code:`age = int(input())\nprint(age)`,options:['"25"',"25","int","Error"],answer:1},
  {id:69,level:2,question:"أي من العبارات التالية صحيحة؟",options:["يمكن أن يبدأ اسم المتغير برقم.","يمكن أن يحتوي اسم المتغير على مسافة.","يمكن استخدام الشرطة (-) داخل اسم المتغير.","يجب أن يبدأ اسم المتغير بحرف أو (_) ولا يحتوي على مسافات."],answer:3},
  {id:70,level:2,question:"أي من الأشكال التالية يُستخدم لتمثيل عملية (Process) في الـ Flowchart؟",options:["Oval","Diamond","Rectangle","Parallelogram"],answer:2},

  // Level 3 (71-100)
  {id:71,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 5\ny = 10\nprint(x < y and y > 8)`,options:["True","False","Error","15"],answer:0},
  {id:72,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 8\nprint(not(x == 8))`,options:["True","False","8","Error"],answer:1},
  {id:73,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`a = 10\nb = 3\nprint(a // b)`,options:["3","3.33","1","30"],answer:0},
  {id:74,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(15 % 4)`,options:["1","2","3","4"],answer:2},
  {id:75,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(3 ** 3)`,options:["6","9","27","81"],answer:2},
  {id:76,level:3,question:"إذا كانت score = 90 فما الناتج؟",isCode:true,code:`score = 90\nif score >= 90:\n    print("Excellent")\nelse:\n    print("Good")`,options:["Good","Excellent","Error","90"],answer:1},
  {id:77,level:3,question:"إذا كانت score = 65 فما الناتج؟",isCode:true,code:`score = 65\nif score >= 70:\n    print("Pass")\nelse:\n    print("Try Again")`,options:["Pass","Try Again","65","Error"],answer:1},
  {id:78,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 10\nprint(x > 5 or x < 3)`,options:["True","False","Error","10"],answer:0},
  {id:79,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 2\nprint(x > 5 and x < 10)`,options:["True","False","2","Error"],answer:1},
  {id:80,level:3,question:"أي نوع بيانات ينتج عن عملية المقارنة؟",options:["int","float","bool","str"],answer:2},
  {id:81,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type(True))`,options:["str","int","bool","float"],answer:2},
  {id:82,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type("True"))`,options:["bool","str","int","float"],answer:1},
  {id:83,level:3,question:"أي من الأوامر التالية يطبع قيمة المتغير age؟",options:["input(age)","print(age)","type(age)","int(age)"],answer:1},
  {id:84,level:3,question:"إذا كانت قيمة المتغير x = 20 فما ناتج الكود؟",isCode:true,code:`x = 20\nprint(x >= 20)`,options:["True","False","Error","20"],answer:0},
  {id:85,level:3,question:"إذا كانت x = 15 فما ناتج الكود؟",isCode:true,code:`x = 15\nprint(x < 10)`,options:["True","False","Error","15"],answer:1},
  {id:86,level:3,question:"أي جهاز من التالي يعد جهاز إخراج؟",options:["Keyboard","Mouse","Monitor","Scanner"],answer:2},
  {id:87,level:3,question:"أي جهاز من التالي يعد جهاز إدخل؟",options:["Printer","Speaker","Keyboard","Monitor"],answer:2},
  {id:88,level:3,question:"أي مكون يخزن البيانات بشكل دائم؟",options:["RAM","HDD","Cache","Register"],answer:1},
  {id:89,level:3,question:"أي مكون يفقد محتوياته عند إيقاف تشغيل الجهاز؟",options:["ROM","HDD","SSD","RAM"],answer:3},
  {id:90,level:3,question:"أي مكون يحتوي على برنامج بدء تشغيل الحاسوب؟",options:["RAM","ROM","SSD","CPU"],answer:1},
  {id:91,level:3,question:"ما أول خطوة في دورة عمل المعالج (CPU)؟",options:["Execute","Decode","Fetch","Store"],answer:2},
  {id:92,level:3,question:"في الـ Flowchart، أي شكل يُستخدم لتمثيل الإدخال والإخراج؟",options:["Rectangle","Diamond","Parallelogram","Oval"],answer:2},
  {id:93,level:3,question:"أي اسم متغير صحيح؟",options:["first-name","student1","1student","my name"],answer:1},
  {id:94,level:3,question:"ما نوع البيانات للقيمة 100؟",options:["float","bool","int","str"],answer:2},
  {id:95,level:3,question:"ما نوع البيانات للقيمة \"100\"؟",options:["int","float","bool","str"],answer:3},
  {id:96,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(type(9.8))`,options:["int","float","bool","str"],answer:1},
  {id:97,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(18 / 6)`,options:["3","3.0","2","6"],answer:1},
  {id:98,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(18 // 6)`,options:["3","3.0","0","6"],answer:0},
  {id:99,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`print(7 + 8 * 2)`,options:["30","23","22","15"],answer:1},
  {id:100,level:3,question:"ما ناتج الكود التالي؟",isCode:true,code:`x = 10\ny = 5\nprint(x == 10 and y == 5)`,options:["True","False","Error","15"],answer:0}
];